const option = {
  l400ChemistrySingleMajorFirstSem: {
    subject1: "CHEM 400 : Project",
    subject2: "CHEM 473 : X-ray Crystallography",
    subject3: "CHEM 401 : Thermodynamics II",
    subject4: "CHEM 403 : Symmetry, Group Theory and Applications",
    subject5: "CHEM 405 : Reaction Kinetics",
    subject6: "CHEM 441 : Chemistry of Natural Products ",
    subject7: "CHEM 439 : Organometallic Chemistry",
    subject8: "CHEM 437 : Medicinal Chemistry",
    subject9: "CHEM 423 : Polymer Chemistry and Tech",
    subject10: "CHEM 471 : Nuclear Chemistry",
    subject11: "CHEM 491 : Petroleum Chemistry and Tech",
    subject12: "CHEM 493 : Mineral Processing",
    subject13: "CHEM 495 : Pulp and Paper Chemistry and Technology",
  },

  l400ChemistrySingleMajorSecondSem: {
    subject1: "CHEM 400 : Project",
    subject2: "CHEM 402 : Quantum Chemistry ",
    subject3: "CHEM 412 : Surface Chemistry Colloids ",
    subject4: "CHEM 454 : Transition Metal Chemistry",
    subject5: "CHEM 472 : Instrumental Methods of Chemical Analysis",
    subject6: "CHEM 414 : Molecular Structure ",
    subject7: "CHEM 452 : Solid State Chemistry",
    subject8: "CHEM 494 : Textile Chemistry and Technology",
    subject9: "CHEM 492 : Industrial Chemistry",
    subject10: "CHEM 474 : Elements of Forensic Chemistry",
    subject11: "CHEM 496 : Environmental Chemistry",
  },

  l400ChemistryCombinedMajorFirstSem: {
    subject1: "CHEM 401 : Thermodynamics II",
    subject2: "CHEM 423 : Polymer Chemistry and Technology",
    subject3: "CHEM 405 : Reaction Kinetics",
    subject4: "CHEM 441 : Chemistry of Natural Products",
    subject5: "CHEM 403 : Symmetry, Group Theory and Application",
    subject6: "CHEM 437 : Medicinal Chemistry",
    subject7: "CHEM 439 : Organometallic Chemistry",
    subject8: "CHEM 471 : Nuclear Chemistry",
    subject9: "CHEM 473 : X-ray Crystallography",
    subject10: "CHEM 491 : Petroleum Chemistry and Technology",
    subject11: "CHEM 493 : Mineral Processing",
    subject12: "CHEM 495 : Pulp and Paper Chemistry and Technology",
  },

  l400ChemistryCombinedMajorSecondSem: {
    subject1: "CHEM 402 : Quantum Chemistry",
    subject2: "CHEM 412 : Surface Chemistry and Colloids",
    subject3: "CHEM 454 : Transition Metal Chemistry",
    subject4: "CHEM 472 : Instrumental Methods of Chemical Analysis",
    subject5: "CHEM 414 : Molecular Structure",
    subject6: "CHEM 492 : Industrial Chemistry",
    subject7: "CHEM 494 : Textile Chemistry and Technology",
    subject8: "CHEM 452 : Solid State Chemistry",
    subject9: "CHEM 474 : Elements of Forensic Chemistry ",
    subject10: "CHEM 496 : Environmental Chemistry",
  },

  l400ComputerScienceSingleMajorFirstSem: {
    subject1: "DCIT 400 : Project",
    subject2: "DCIT 401 : Social, Legal, Ethical and Professional Issues",
    subject3: "DCIT 407 : Image Processing",
    subject4: "DCIT 403 : Designing Intelligent Agents",
    subject5: "DCIT 405 : Statistical Models  and Methods for Data Science",
    subject6: "DCIT 411 : Bioinformatics",
    subject7: "DCIT 417 : Network Performance Analysis and Modeling",
    subject8: "DCIT 423 : Network Servers and Infrastructure",
  },

  l400ComputerScienceSingleMajorSecondSem: {
    subject1: "DCIT 400 : Project",
    subject2: "DCIT 402 : Management Principles in Computing",
    subject3: "DCIT 418 : Systems and Network Security",
    subject4: "DCIT 428 : Wireless Systems and Networks",
    subject5: "DCIT 404 : Advanced Databases",
    subject6: "DCIT 406 : Advanced Computer Networks",
    subject7: "DCIT 408 : Compilers",
    subject8: "DCIT 426 : Telecommunication Systems",
    subject9: "DCIT 412 : Computer Vision",
    subject10: "DCIT 414 : Data Mining and Warehousing",
    subject11: "DCIT 416 : Digital Signal Processing",
    subject12: "DCIT 422 : Information Visualization",
  },

  l400ComputerScienceCombinedFirstSem: {
    subject1: "DCIT 400 : Project",
    subject2: "DCIT 401 : Social, Legal, Ethical and Professional Issues",
    subject3: "DCIT 407 : Image Processing",
    subject4: "DCIT 403 : Designing Intelligent Agents",
    subject5: "DCIT 405 : Statistical Models  and Methods for Data Science",
    subject6: "DCIT 411 : Bioinformatics",
    subject7: "DCIT 417 : Network Performance Analysis and Modeling",
    subject8: "DCIT 423 : Network Servers and Infrastructure",
  },

  l400ComputerScienceCombinedSecondSem: {
    subject1: "DCIT 400 : Project",
    subject2: "DCIT 402 : Management Principles in Computing",
    subject3: "DCIT 418 : Systems and Network Security",
    subject4: "DCIT 428 : Wireless Systems and Networks",
    subject5: "DCIT 404 : Advanced Databases",
    subject6: "DCIT 406 : Advanced Computer Networks",
    subject7: "DCIT 408 : Compilers",
    subject8: "DCIT 426 : Telecommunication Systems",
    subject9: "DCIT 412 : Computer Vision",
    subject10: "DCIT 414 : Data Mining and Warehousing",
    subject11: "DCIT 416 : Digital Signal Processing",
    subject12: "DCIT 422 : Information Visualization",
  },

  l400InformationTechnologyFirstSem: {
    subject1: "DCIT 400 : Project",
    subject2: "DCIT 401 : Social, Legal, Ethical and Professional Issues",
    subject3: "DCIT 409 : Digital Forensics",
    subject4: "DCIT 413 : Play and Games",
    subject5: "DCIT 415 : Advanced Software Engineering",
    subject6: "DCIT 419 : Agile Methods",
    subject7: "DCIT 421 : Persuasive Systems Development",
  },

  l400InformationTechnologySecondSem: {
    subject1: "DCIT 400 : Project 3",
    subject2: "DCIT 402 : Management Principles in Computing",
    subject3: "DCIT 418 : Systems and Network Security ",
    subject4: "DCIT 428 : Wireless Systems and Networks",
    subject5: "DCIT 404 : Advanced Databases",
    subject6: "DCIT 406 : Advanced Computer Networks",
    subject7: "DCIT 408 : Compilers",
    subject8: "DCIT 426 : Telecommunication Systems",
    subject9: "DCIT 412 : Computer Vision",
    subject10: "DCIT 414 : Data Mining and Warehousing",
    subject11: "DCIT 416 : Digital Signal Processing",
    subject12: "DCIT 422 : Information Visualization",
  },

  l400EarthScienceSingleMajorFirstSem: {
    subject1: "EASC 420 : Project",
    subject2: "EASC 471 : Remote Sensing and Geographic Information Systems",
    subject3: "EASC 450 : Geological Field Mapping",
    subject4: "EASC 419 : Igneous and Metamorphic Petrology",
    subject5: "EASC 417 : Mineralogy",
    subject6: "EASC 437 : Geochemistry and Cosmochemistry",
    subject7: "EASC 465 : Micropaleontology",
    subject8: "EASC 461 : Basin Analysis",
    subject9: "EASC 449 : Mineral Exploration Methods, Planning and Management",
  },

  l400EarthScienceSingleMajorSecondSem: {
    subject1: "EASC 420 : Project",
    subject2: "EASC 404 : Statistical Methods in Earth Science ",
    subject3: "EASC 480 : Field Studies in Earth Science",
    subject4: "EASC 470 : Communication and  Entrepreneurship in the Earth Sciences",
    subject5: "EASC 446 : Sedimentary Petrology",
    subject6: "EASC 448 : Geology of Africa",
    subject7: "EASC 454 : Geochronology",
    subject8: "EASC 476 : Geotectonics",
    subject9: "EASC 478 : Stratigraphy",
    subject10: "EASC 482 : Geology of Mineral Deposits",
  },

  l400GeologyMajorMinorFirstSem: {
    subject1: "EASC 420 : Project",
    subject2: "EASC 471 : Remote Sensing and Geographic Information Systems",
    subject3: "EASC 450 : Geological Field Mapping",
    subject4: "EASC 419 : Igneous and Metamorphic Petrology",
    subject5: "EASC 417 : Mineralogy",
    subject6: "EASC 437 : Geochemistry and Cosmochemistry",
    subject7: "EASC 465 : Micropaleontology",
    subject8: "EASC 461 : Basin Analysis",
  },

  l400GeologyMajorMinorSecondSem: {
    subject1: "EASC 420 : Project",
    subject2: "EASC 404 : Statistical Methods in Earth Science ",
    subject3: "EASC 480 : Field Studies in Earth Science",
    subject4: "EASC 470 : Communication and  Entrepreneurship in the Earth Sciences",
    subject5: "EASC 446 : Sedimentary Petrology",
    subject6: "EASC 448 : Geology of Africa ",
    subject7: "EASC 454 : Geochronology",
    subject8: "EASC 476 : Geotectonics",
    subject9: "EASC 478 : Stratigraphy",
    subject10: "EASC 482 : Geology of Mineral Deposits",
  },

  l400MathSingleMajorFirstSem: {
    subject1: "MATH 400 : Project",
    subject2: "MATH 441 : Advanced Calculus",
    subject3: "MATH 440 : Abstract Algebra II",
    subject4: "MATH 447 : Complex Analysis",
    subject5: "MATH 443 : Differential Geometry",
    subject6: "MATH 445 : Introductory Functional Analysis",
    subject7: "MATH 449 : Electromagnetic Theory II",
    subject8: "MATH 451 : Introduction to Algebraic Field Theory",
    subject9: "MATH 453 : Introduction to Quantum Mechanics",
    subject10: "MATH 455 : Computational Mathematics II",
    subject11: "MATH 457 : Mathematical Biology I",
  },

  l400MathSingleMajorSecondSem: {
    subject1: "MATH 400 : Project 3",
    subject2: "MATH 442 : Integration Theory and Measure",
    subject3: "MATH 440 : Abstract Algebra II",
    subject4: "MATH 444 : Calculus on Manifolds ",
    subject5: "MATH 446 : Module Theory",
    subject6: "MATH 448 : Special Relativity",
    subject7: "MATH 452 : Introduction to Lie Groups and Lie Algebra",
    subject8: "MATH 450 : Differential Equations II",
    subject9: "MATH 458 : Mathematical Biology II",
    subject10: "MATH 460 :  Fourier series and Fourier transforms",
  },

  l400MathMajorMinorFirstSem: {
    subject1: "MATH 400 : Project",
    subject2: "MATH 441 : Advanced Calculus",
    subject3: "MATH 440 : Abstract Algebra II",
    subject4: "MATH 447 : Complex Analysis",
    subject5: "MATH 443 : Differential Geometry",
    subject6: "MATH 445 : Introductory Functional Analysis",
    subject7: "MATH 449 : Electromagnetic Theory II",
    subject8: "MATH 451 : Introduction to Algebraic Field Theory",
    subject9: "MATH 453 : Introduction to Quantum Mechanics",
    subject10: "MATH 455 : Computational Mathematics II",
    subject11: "MATH 457 : Mathematical Biology I",
  },

  l400MathMajorMinorSecondSem: {
    subject1: "MATH 400 : Project 3",
    subject2: "MATH 442 : Integration Theory and Measure",
    subject3: "MATH 444 : Calculus on Manifolds ",
    subject4: "MATH 446 : Module Theory",
    subject5: "MATH 448 : Special Relativity",
    subject6: "MATH 452 : Introduction to Lie Groups and Lie Algebra",
    subject7: "MATH 450 : Differential Equations II",
    subject8: "MATH 458 : Mathematical Biology II",
    subject9: "MATH 460 : Fourier series and Fourier transforms",
  },

  l400MathCombinedMajorFirstSem: {
    subject1: "MATH 441 : Advanced Calculus",
    subject2: "MATH 447 : Complex Analysis",
    subject3: "MATH 440 : Abstract Algebra II",
    subject4: "MATH 443 : Differential Geometry",
    subject5: "MATH 445 : Introductory Functional Analysis",
    subject6: "MATH 449 : Electromagnetic theory II",
    subject7: "MATH 451 : Introduction to Algebraic Field Theory",
    subject8: "MATH 453 : Introduction to Quantum Mechanics",
    subject9: "MATH 455 : Computational Mathematics II",
    subject10: "MATH 457 : Mathematical Biology I",
  },

  l400MathCombinedMajorSecondSem: {
    subject1: "MATH 442 : Integration Theory and Measure",
    subject2: "MATH 372 : Topology",
    subject3: "MATH 444 : Calculus on Manifolds ",
    subject4: "MATH 446 : Module Theory",
    subject5: "MATH 448 : Special Relativity",
    subject6: "MATH 452 : Introduction to Lie Groups and Lie Algebra",
    subject7: "MATH 450 : Differential Equations II",
    subject8: "MATH 458 : Mathematical Biology II",
    subject9: "MATH 460 : Fourier series and Fourier transforms",
  },

  l400PhysicsMajorFirstSem: {
    subject1: "PHYS 410 : Project",
    subject2: "PHYS 401 : Seminar I",
    subject3: "PHYS 443 : Statistical Mechanics",
    subject4: "PHYS 459 : Solid State Physics II",
    subject5: "PHYS 447 : Electronics II",
    subject6: "PHYS 455 : Energy Systems",
    subject7: "PHYS 461 : Principles of Radioactive Dating",
    subject8: "PHYS 465 : Physics of Telecommunications",
  },

  l400PhysicsMajorSecondSem: {
    subject1: "PHYS 410 : Project",
    subject2: "PHYS 402 : Seminar II",
    subject3: "PHYS 446 : Nuclear Physics II",
    subject4: "PHYS 448 : Particle Physics",
    subject5: "PHYS 452 : Quantum Mechanics II",
    subject6: "PHYS 454 : Contemporary Physics",
    subject7: "PHYS 468 : Introduction to Cosmology and Astrophysics",
    subject8: "PHYS 462 : Basic Meteorology",
    subject9: "PHYS 466 : Physics at Nanoscale",
  },

  l400PhysicsMajorMinorFirstSem: {
    subject1: "PHYS 410 : Project",
    subject2: "PHYS 401 : Seminar I",
    subject3: "PHYS 443 : Statistical Mechanics",
    subject4: "PHYS 449 : Physics of Solids",
    subject5: "PHYS 447 : Electronics II",
    subject6: "PHYS 455 : Energy Systems",
    subject7: "PHYS 461 : Principles of Radioactive Dating",
    subject8: "PHYS 465 : Physics of Telecommunications",
  },

  l400PhysicsMajorMinorSecondSem: {
    subject1: "PHYS 410 : Project",
    subject2: "PHYS 402 : Seminar II",
    subject3: "PHYS 446 : Nuclear Physics II",
    subject4: "PHYS 448 : Particle Physics",
    subject5: "PHYS 452 : Quantum Mechanics II",
    subject6: "PHYS 454 : Contemporary Physics",
    subject7: "PHYS 468 : Introduction to Cosmology and Astrophysics",
    subject8: "PHYS 462 : Basic Meteorology",
    subject9: "PHYS 466 : Physics at Nanoscale",
  },

  l400PhysicsCombinedMajorFirstSem: {
    subject1: "PHYS 443 : Statistical Mechanics",
    subject2: "PHYS 449 : Physics of Solids",
    subject3: "PHYS 410 : Project",
    subject4: "PHYS 401 : Seminar I",
    subject5: "PHYS 447 : Electronics II",
    subject6: "PHYS 455 : Energy Systems",
    subject7: "PHYS 461 : Principles of Radioactive Dating",
    subject8: "PHYS 465 : Physics of Telecommunications",
  },

  l400PhysicsCombinedMajorSecondSem: {
    subject1: "PHYS 410 : Project",
    subject2: "PHYS 402 : Seminar II",
    subject3: "PHYS 446 : Nuclear Physics II",
    subject4: "PHYS 448 : Particle Physics",
    subject5: "PHYS 452 : Quantum Mechanics II",
    subject6: "PHYS 454 : Contemporary Physics",
    subject7: "PHYS 468 : Introduction to Cosmology and Astrophysics",
    subject8: "PHYS 462 : Basic Meteorology",
    subject9: "PHYS 466 : Physics at Nanoscale",
  },

  l400GeophysicsFirstSem: {
    subject1: "PHYS 401 : Seminar I",
    subject2: "PHYS 447 : Electronics II",
    subject3: "PHYS 443 : Statistical Mechanics",
    subject4: "PHYS 449 : Physics of Solids",
    subject5: "PHYS 455 : Energy systems",
    subject6: "PHYS 461 : Principles of Radioactive Dating",
    subject7: "EASC 401 : Remote Sensing and Geographic Information Systems",
    subject8: "EASC 451 : Rock Mechanics",
    subject9: "EASC 423 : Hydrogeology",
    subject10: "GPHY 400 : Project",
    subject11: "GPHY 403 : Geophysical Instrumentation and Techniques",
  },

  l400GeophysicsSecondSem: {
    subject1: "EASC 428 : Exploration Geophysics",
    subject2: "EASC 442 : Petroleum Reservoir Geophysics",
    subject3: "EASC 452 : Site Investigations",
    subject4: "PHYS 402 : Seminar II",
    subject5: "EASC 404 : Statistical Methods in Earth Science",
    subject6: "PHYS 446 : Nuclear Physics II",
    subject7: "PHYS 448 : Particle Physics",
    subject8: "PHYS 462 : Basic Meteorology",
    subject9: "PHYS 468 : Introduction to Cosmology and Astrophysics",
  },

  l400StatisticsSingleMajorFirstSem: {
    subject1: "STAT 443 : Theory of Sampling",
    subject2: "STAT 445 : Advanced Regression",
    subject3: "STAT 450 : Project",
    subject4: "STAT 461 : Bayesian Statistics",
    subject5: "STAT 440 : Business Statistics",
    subject6: "STAT 447 : Non-Parametric Statistics",
    subject7: "STAT 451 : Random Processes",
    subject8: "STAT 453 : Population Statistics",
    subject9: "STAT 459 : Statistical Quality Control",
    subject10: "STAT 455 : Actuarial Statistics I",
    subject11: "STAT 457 : Economic and Social Statistics I",
    subject12: "MATH 441 : Advanced Calculus",
    subject13: "MATH 445 : Introductory Functional Analysis",
  },

  l400StatisticsSingleMajorSecondSem: {
    subject1: "STAT 444 : Survey Organisation and Management",
    subject2: "STAT 466 : Discrete Data Analysis",
    subject3: "STAT 450 : Project",
    subject4: "STAT 442 : Applied Times Series Analysis",
    subject5: "STAT 446 : Multivariate Methods",
    subject6: "STAT 448 : Analysis of Experimental Design",
    subject7: "STAT 464 : Statistical Computing with R",
    subject8: "STAT 454 : Biometrics",
    subject9: "STAT 456 : Actuarial Statistics II",
    subject10: "STAT 458 : Economic and Social Statistics II ",
    subject11: "STAT 462 : Biostatistics",
    subject12: "MATH 422 : Integration Theory and Measure",
    subject13: "MATH 450 : Differential Equation II",
  },

  l400StatisticsMajorMinorFirstSem: {
    subject1: "STAT 443 : Theory of Sampling",
    subject2: "STAT 445 : Advanced Regression",
    subject3: "STAT 450 : Project",
    subject4: "STAT 461 : Bayesian Statistics",
    subject5: "STAT 440 : Business Statistics",
    subject6: "STAT 447 : Non-Parametric Statistics",
    subject7: "STAT 451 : Random Processes",
    subject8: "STAT 453 : Population Statistics",
    subject9: "STAT 459 : Statistical Quality Control",
    subject10: "STAT 455 : Actuarial Statistics I",
    subject11: "STAT 457 : Economic and Social Statistics I",
  },

  l400StatisticsMajorMinorSecondSem: {
    subject1: "STAT 444 : Survey Organisation and Management",
    subject2: "STAT 466 : Discrete Data Analysis",
    subject3: "STAT 450 : Project",
    subject4: "STAT 442 : Applied Times Series Analysis",
    subject5: "STAT 446 : Multivariate Methods",
    subject6: "STAT 464 : Statistical Computing with R",
    subject7: "STAT 454 : Biometrics",
    subject8: "STAT 456 : Actuarial Statistics II",
    subject9: "STAT 458 : Economic and Social Statistics II ",
    subject10: "STAT 462 : Biostatistics",
    subject11: "MATH 422 : Integration Theory and Measure",
    subject12: "MATH 450 : Differential Equation II",
  },

  l400StatisticsCombinedMajorFirstSem: {
    subject1: "STAT 443 : Theory of Sampling",
    subject2: "STAT 445 : Advanced Regression Analysis",
    subject3: "STAT 440 : Business Statistics",
    subject4: "STAT 447 : Non-Parametric Statistics",
    subject5: "STAT 450 : Project",
    subject6: "STAT 451 : Random Processes",
    subject7: "STAT 453 : Population Statistics",
    subject8: "STAT 455 : Actuarial Statistics I",
    subject9: "STAT 457 : Economic and Social Statistics I",
    subject10: "STAT 459 : Statistical Quality Control",
    subject11: "STAT 461 : Bayesian Statistics Methods",
  },

  l400StatisticsCombinedMajorSecondSem: {
    subject1: "STAT 444 : Survey Organisation and Management",
    subject2: "STAT 448 : Analysis of Experimental design",
    subject3: "STAT 450 : Project",
    subject4: "STAT 446 : Multivariate Methods",
    subject5: "STAT 464 : Statistical Computing with R",
    subject6: "STAT 454 : Biometrics",
    subject7: "STAT 456 : Actuarial Statistics II",
    subject8: "STAT 458 : Economic and Social Statistics II ",
    subject9: "STAT 466 : Discrete Data Analysis",
  },

  l400ActurialScienceSingleMajorFirstSem: {
    subject1: "ACTU 410 : Project",
    subject2: "ACTU 405 : Fundamentals of Financial Accounting I",
    subject3: "ACTU 409 : Loss Distributions & Actuarial Risk Measures",
    subject4: "ACTU 453 : Introduction to Non-Life Insurance Mathematics I",
    subject5: "ACTU 407 : Financial Economics I",
    subject6: "STAT 457 : Economic and Social Statistics II",
    subject7: "STAT 445 : Advanced Regression Analysis",
    subject8: "ACTU 445 : Macroeconomic Theory for Actuaries I",
    subject9: "STAT 443 : Population Statistics",
    subject10: "STAT 451 : Random Processes",
    subject11: "MATH 441 : Advanced Calculus",
    subject12: "MATH 445 : Introductory Functional Analysis",
    subject13: "ACTU 441 : Econometrics for Actuaries I",
    subject14: "MATH 447 : Complex Analysis",
    subject15: "STAT 459 : Statistical Quality Control",
    subject16: "STAT 440 : Business Statistics",
  },

  l400ActurialScienceSingleMajorSecondSem: {
    subject1: "ACTU 410 : Project",
    subject2: "ACTU 412 : Fundamental Financial Accounting II",
    subject3: "ACTU 454 : Introduction to Non-life Insurance Mathematics II",
    subject4: "ACTU 408 : Financial Economics II",
    subject5: "ACTU 404 : Pensions and Social Security",
    subject6: "MATH 442 : Differential Equation II",
    subject7: "ACTU 448 : Macroeconomic Theory for Actuaries II",
    subject8: "FINC 458 : Health Insurance",
    subject9: "STAT 458 : Economic and Social Statistics II",
    subject10: "ACTU 442 : Econometrics for Actuaries II",
    subject11: "FINC 452 : Property and Pecuniary Insurance",
  },

  l400ActurialScienceAndMathCombinedMajorFirstSem: {
    subject1: "ACTU 403 : Introduction to Non-Life Insurance Mathematics I",
    subject2: "ACTU 405 : Fundamentals of Financial Accounting I",
    subject3: "ACTU 407 : Financial Economics I",
    subject4: "ACTU 409 : Loss Distributions & Actuarial Risk Measures",
    subject5: "MATH 441 : Advanced Calculus",
    subject6: "MATH 445 : Introductory Functional Analysis",
    subject7: "STAT 440 : Business Statistics",
    subject8: "STAT 451 : Random Processes",
    subject9: "ACTU 443 : Econometrics for Actuaries I",
    subject10: "STAT 443 : Population Statistics",
    subject11: "STAT 445 : Advanced Regression Analysis",
    subject12: "ACTU 445 : Macroeconomic Theory for Actuaries I",
    subject13: "MATH 447 : Complex Analysis",
    subject14: "STAT 457 : Economic and Social Statistics I",
    subject15: "STAT 459 : Statistical Quality Control",
  },

  l400ActurialScienceAndMathCombinedMajorSecondSem: {
    subject1: "ACTU 404 : Pensions and Social Security",
    subject2: "ACTU 412 : Fundamental Financial Accounting II",
    subject3: "MATH 442 : Integration and Measure Theory",
    subject4: "ACTU 444 : Introduction Non-life Insurance Mathematics II",
    subject5: "ACTU 408 : Financial Economics II",
    subject6: "ACTU 442 : Econometrics for for Actuaries II",
    subject7: "ACTU 448 : Macroeconomic Theory for Actuaries II",
    subject8: "MATH 450 : Differential Equation II",
    subject9: "FINC 452 : Property and Pecuniary Insurance",
    subject10: "FINC 458 : Health Insurance",
    subject11: "STAT 458 : Economic and Social Statistics II",
  },
};
